### ISSUE TITLE
etn pool for Install 

### ISSUE THREAD

**Issue by MrCoolLV** [electroneum/electroneum-pool#102]
@electroneumRepo
PM me, etn price for install ?

**Comment by ddvs1** [comment]
You need help for install a pool ?

**Comment by electroneumRepo** [comment]
@MrCoolLV are you requesting a cost for installing the pool for you?

**Comment by MrCoolLV** [comment]
yes, credit card, btc, eth, or etn.

ivanjr@nocroom.com

**Comment by MrCoolLV** [comment]
@electroneumRepo

**Comment by Zer0dn** [comment]
I will do it for 1,000 coins
