### ISSUE TITLE
about first page

### ISSUE THREAD

**Issue by makyar** [electroneum/electroneum-pool#103]
Hi developers, thank you for this project.
I installed and configured in my server.
but one person write address etn.shockcoin.com, main page empty 
if I clicked again Home link.
the site is working properly

**Comment by electroneumRepo** [comment]
Hi @makyar,

It seems that your homepage is broken. This was fixed some time ago.

If you click on the "Home" link then this loads the main page up. I'm not sure why this would be happening now as it was previously fixed quite some time ago. I'll take a look into this further
