### ISSUE TITLE
Does not start mining Electroneum

### ISSUE THREAD

**Issue by Pok76** [electroneum/electroneum-pool#108]
Hi,

I hope somebody can help me out a little because i am kind of new at this

i downloaded the mac direct miner and it seems to be syncing fine. Once I type the command start_mining <wallet address> <threads> (2 threads in my case) i keep getting the error

Error: Mining did not start -- BUSY

At this point i have no idea how to fix this. Anybody who can help with this problem?

Thanks ahead

**Comment by electroneumRepo** [comment]
Hi @Pok76,

You need to wait for the syncing to complete before you can start mining

**Comment by ivoryz** [comment]
Hello @electroneumRepo,
after the sync, I executed the command “start_mining my_etn_address 7”, my pc is mining for 5 days, where I can see how many ETN I already mined?
