### ISSUE TITLE
When lauch coin daemon get WARN    net.dns src/common/dns_utils.cpp:487    WARNING: no two valid ElectroneumPulse DNS checkpoint records were received

### ISSUE THREAD

**Issue by neurans** [electroneum/electroneum-pool#11]
getting  WARNING: no two valid ElectroneumPulse DNS checkpoint records were received on coin daemon start. IS this just a warning? or an issue?

**Comment by jeerdo** [comment]
So was it just a warning or an issue? Cause i'm having the same..

**Comment by gasiferox** [comment]
me too
