### ISSUE TITLE
front end problem

### ISSUE THREAD

**Issue by coreytaylor211** [electroneum/electroneum-pool#112]
Hi I have a problem with my front end, it don´t show any stats but all modules are running good. The page show an infinty loading circle. Here are my configs : `var api = "http://xx.xxx.xxx.xxx:8117";

var coinUnits = 100;
var coinDecimalPlaces = 2;

var poolHost = "http://xx.xxx.xxx.xxx";

var irc = "irc.freenode.net/#monero-pools";

var email = "xxx@gmx.de";

var easyminerDownload = "https://github.com/zone117x/cryptonote-easy-miner/releases/";

var blockchainExplorer = "https://blockexplorer.electroneum.com/block/";

var transactionExplorer = "https://blockexplorer.electroneum.com/tx/";` and here the other config `{
    "coin": "electroneum",
    "symbol": "ETN",
    "logging": {
        "files": {
            "level": "info",
            "directory": "logs",
            "flushInterval": 5
        },

        "console": {
            "level": "info",
            "colors": true
        }
    },
    "poolServer": {
        "enabled": true,
        "clusterForks": "auto",
        "poolAddress": "etnk4g5dm5q1Afs36Z2vsxRY1JrkkjLh1N9Xf2bBiGqPTyG4f8miFnVViWq3f5BziqT8L9LxiZ66yRv9X7w6152e7opCj859BR",
        "blockRefreshInterval": 1000,
        "minerTimeout": 900,
        "ports": [
            {
                "port": 3333,
                "difficulty": 5000,
                "desc": "Low end hardware"
            },
            {
                "port": 5555,
                "difficulty": 25000,
                "desc": "Mid range hardware"
            },
            {
                "port": 7777,
                "difficulty": 50000,
                "desc": "High end hardware"
            }
        ],
        "varDiff": {
            "minDiff": 2,
            "maxDiff": 100000,
            "targetTime": 100,
            "retargetTime": 30,
            "variancePercent": 30,
            "maxJump": 100
        },
        "shareTrust": {
            "enabled": true,
            "min": 10,
            "stepDown": 3,
            "threshold": 10,
            "penalty": 30
        },
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 25,
            "checkThreshold": 30
        },
        "slushMining": {
            "enabled": false,
            "weight": 300,
            "lastBlockCheckRate": 1
        }
    },
    "payments": {
        "enabled": true,
        "interval": 600,
        "maxAddresses": 10,
        "mixin": 0,
        "transferFee": 1,
        "minPayment": 5000,
        "denomination": 100
    },
    "blockUnlocker": {
        "enabled": true,
        "interval": 30,
        "depth": 20,
        "poolFee": 1.8,
        "devDonation": 0.1,
        "coreDevDonation": 0.1
    },
    "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 3,
        "port": 8117,
        "blocks": 30,
        "payments": 30,
        "password": "test"
    },
    "daemon": {
        "host": "127.0.0.1",
        "port": 26968
    },
    "wallet": {
        "host": "127.0.0.1",
        "port": 26969
    },
    "redis": {
        "host": "127.0.0.1",
        "port": 6379,
        "auth": null
    }
}
` what is the problem ? plz help :)

**Comment by vipurkumar** [comment]
@coreytaylor211 : did you try running only api module and seeing any diff ? `node init.js -module=api`

**Comment by coreytaylor211** [comment]
@vipurkumar Yes, nur it is the same. :(

**Comment by vipurkumar** [comment]
@coreytaylor211 : thats strange. whats the output for http://xx.xxx.xxx.xxx:8117/stats. Also do fire up the firebug and see which call is getting stuck..

**Comment by coreytaylor211** [comment]
Ok the output is '    {"config":{"ports":[{"port":3333,"difficulty":5000,"desc":"Low end hardware"},{"port":5555,"difficulty":25000,"desc":"Mid range hardware"},{"port":7777,"difficulty":50000,"desc":"High end hardware"}],"hashrateWindow":600,"fee":1.8,"coin":"electroneum","symbol":"ETN","depth":20,"donation":0.1,"coreDonation":0.1,"doDonations":false,"version":"v0.99.3.3","minPaymentThreshold":5000,"denominationUnit":100,"slushMiningEnabled":false,"weight":300},"network":{"difficulty":11319258936,"height":78947,"timestamp":1513962905,"reward":743384,"hash":"e68bd2dc1286be68561dd3b1c655d0501309b29d9a796dcb7209d8b739685f4c"},"pool":{"stats":null,"blocks":[],"totalBlocks":0,"payments":[],"totalPayments":0,"totalMinersPaid":-1,"miners":1,"hashrate":38.315,"roundHashes":6952182}} '

**Comment by m3nt0l** [comment]
Maybe you run this with having a SSL:), does your  website have https:// in from of the link?

If yes,you  need to connect to your API SSL port:)

**Comment by noob1313** [comment]
@m3nt0l You say to connect the API SSL port. I am trying to run my front end on Plesk which you may not know about but it uses Apache/nginx I can't figure out how to make the page connect to 8117 if the page is loaded with https no issues if http.  If you have any tips that might point me in the right direction I have spent the weekend searching without luck. Thank you
