### ISSUE TITLE
Wallet Balance

### ISSUE THREAD

**Issue by ltduc** [electroneum/electroneum-pool#122]
Dear Team!

I newbie. I use "Beginner's Pool Mining Software". I mine on eu pool and I  receive Total Paid: 20.00 ETN but I check on electroneum-wallet-cli then Balance: 0.

My Address: etnkCrCBjRoPfgnaeozbg9St2ZDfhZchnKkNRmTN6Ljk5EjkfHFJsBPW9x6PcRvg34eu8p6NFwXBqQao7d5JNut91yStce6xk2
My Transaction Hash: 111963cc550e3e8fa791c626bc2d3d7bd61235dac79a4909e1d27c1aeeeb8c7e

I don't understand know. Please, help for me!

Thanks!

![error1](https://user-images.githubusercontent.com/11805724/34370701-ebc0974e-eaf8-11e7-951d-b396c30b2f24.png)
![error2](https://user-images.githubusercontent.com/11805724/34370702-ebe836c8-eaf8-11e7-9478-0e616e1842e0.png)

**Comment by sudeepb02** [comment]
@ltduc Your wallet is 24 days behind present day. For your balance to appear on your wallet, your daemon should be synced till the date your payment was made.

Let it sync or import your wallet on electroneum website or app.

**Comment by ltduc** [comment]
Thanks very much!
