### ISSUE TITLE
Front end issue

### ISSUE THREAD

**Issue by Andrii78** [electroneum/electroneum-pool#128]
Hi all,

I have an issue with my front end - default page shows infinity loading circle. At the same time I can open http://xxx.xxx.xxx.xxx:8117/stats, it shows all the details 

If i open http://xxx.xxx.xxx.xxx:8117/api I got following error: Invalid API call

config.js
var api = "http://xxx.xxx.xxx.xxx:8117/api";

var coinUnits = 100;
var coinDecimalPlaces = 2;

var poolHost = "xxx.xxx.xxx.xxx";
var irc = "irc.freenode.net/#monero-pools";
var email = "support@electroneum.com";
var easyminerDownload = "https://github.com/zone117x/cryptonote-easy-miner/releases/";
var blockchainExplorer = "https://blockexplorer.electroneum.com/block/";
var transactionExplorer = "https://blockexplorer.electroneum.com/tx/";

part of config.json
...
    },
    "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 3,
        "port": 8117,
        "blocks": 30,
        "payments": 30,
        "password": "xxxxxx"
    },

Could you assist please with further troubleshooting steps?

Many Thanks,
Andrii

**Comment by electroneumRepo** [comment]
Hi,

Firstly, opening http://xxx.xxx.xxx.xxx:8117/api should correctly display that error because that is not a valid api call.

You do not need the /api if your going directly to the api via the port.

This may fix your loading circle issue.

I hope this helps.

P.S: I recommend that you change the support email address to one of your own as we will be unable to help people are having issues with your pool.

**Comment by Andrii78** [comment]
Hi,

thanks for prompt reply! 

I changed 
var api = "http://xxx.xxx.xxx.xxx:8117/api"; 

to  

var api = "http://xxx.xxx.xxx.xxx:8117/"; 

but this didn't help, still see the loading circle. At the same time, if I go to http://xxx.xxx.xxx.xxx:8117/ I get "Invalid API call" message, so I thin API is up and listening for requests.

Any other suggestions will be greatly appreciated :-)

Thank you!

P.S.
Sure, I will update the support email address to a proper one.

**Comment by Andrii78** [comment]
could these settings in config.json somehow affect the web site?

        },
        "daemon": {
            "host": "0.0.0.0",
            "port": 26968
        },
        "wallet": {
            "host": "0.0.0.0",
            "port": 26969
        },
        "redis": {
            "host": "0.0.0.0",
            "port": 6379,
            "auth": null
        }

Thanks!

**Comment by Andrii78** [comment]
output of http://xxx.xxx.xxx.xxx:8117/stats

ports |  
-- | --
0 |  
port | 3333
difficulty | 100
desc | "Low end hardware"
1 |  
port | 5555
difficulty | 2000
desc | "Mid range hardware"
2 |  
port | 7777
difficulty | 10000
desc | "High end hardware"
hashrateWindow | 600
fee | 0
coin | "electroneum"
symbol | "ETN"
depth | 20
donation | 0
coreDonation | 0
doDonations | false
version | "v0.99.3.3"
minPaymentThreshold | 1
denominationUnit | 0.1
slushMiningEnabled | false
weight | 300
pool |  
stats | null
blocks | []
totalBlocks | 0
payments | []
totalPayments | 0
totalMinersPaid | -1
miners | 0
hashrate | 0
roundHashes | 28000654
network |  
difficulty | 11247369046
height | 89196
timestamp | 1514579742
reward | 731306

**Comment by Andrii78** [comment]
I think I found a reason of the issue:  index.html had following setting

url: api + '/live_stats',

I replaced '/live_stats', to '/stats',

and now it works like a charm :-)
