### ISSUE TITLE
Electroneum API does not work

### ISSUE THREAD

**Issue by dimitrkovalsky** [electroneum/electroneum-pool#132]
Hi, I am trying to run electroneum pool but I get problem with website. I can not get stats from server.
I see :8117/api/stats Failed to load resource: the server responded with a status of 404 (Not Found).
When I trying to call stats from browser (http://electroneum.pp.ua:8117/api/stats) I get Invalid API call.

Here is my config file for pool
` "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 3,
        "port": 8117,
        "blocks": 30,
        "payments": 30,
	"password": "****"
    }`
Conffig on website
var api = "http://electroneum.pp.ua:8117/api";
var coinUnits = 100;
var coinDecimalPlaces = 2;
var poolHost = "electroneum.pp.ua";
var irc = "irc.freenode.net/#monero-pools";
var email = "support@electroneum.com";
var easyminerDownload = "https://github.com/zone117x/cryptonote-easy-miner/releases/";
var blockchainExplorer = "https://blockexplorer.electroneum.com/block/";
var transactionExplorer = "https://blockexplorer.electroneum.com/tx/";

What about password? Is it wallet password or password for api calls? Do I need to setup it in website?
Thanks for your help

**Comment by dimitrkovalsky** [comment]
I found problem. Need to use var api = "http://electroneum.pp.ua:8117"; without /api.

**Comment by electroneumRepo** [comment]
Glad you got it sorted.
