### ISSUE TITLE
ETN Address+PaymentId

### ISSUE THREAD

**Issue by sanich-rd** [electroneum/electroneum-pool#134]
The problem is the settings for the mining pool to the exchange.
How can I add the ability for a user ETH Address+PaymentId???
Those who have experience please tell me. In some settings you can change the code?

Everything else works without problems! Thank you!

**Comment by sanich-rd** [comment]
Another question how to add the ability to show stats for one user with a different rig?

**Comment by electroneumRepo** [comment]
Hi, 
This is not something that is currently coded in to be handled.
Mining to an exchange is a bad idea and should not be encouraged.

**Comment by sanich-rd** [comment]
Thank you! You very much for the reply. I somewhat agree with You! I'm invited to work for upgrading Your project have two strong programmers, will try to organize a project which is still there. Comfortable, with pool with weekly gifts for the miners. Tell me if you have any questions on the network You can apply? Our work will begin within a month. Our pool will newpool.pw. Thank You for such a beautiful Coin!
