### ISSUE TITLE
How do we know if it's working?

### ISSUE THREAD

**Issue by richardmadison** [electroneum/electroneum-pool#14]
Are there any tests or anything we can do to verify we've done everything correct before we invite the public to our pool?

**Comment by neurans** [comment]
Just mine on it yourself for sometime and invite people to test it. 

Quick question, where did you configure the website listening port? Mi Server is Mining but is not listening to port 80.

**Comment by richardmadison** [comment]
Yeah that's not a great way to see if it's working but it appears to be the only way right now...

For the website we just ran these cmd:

cd ~/pool/website_example (or wherever your pool website_example folder is)

python3 -m http.server 80

We are not live yet - we will setup nginx or something a bit more resilient than the python web server when we go live.  If you are running another webserver and having problems, verify that port 80 is not firewalled.
