### ISSUE TITLE
Payment miner pool eu

### ISSUE THREAD

**Issue by ltduc** [electroneum/electroneum-pool#141]
Dear, Team!

A few last day, I don't receive for payment pool eu!

Please, support for me!

Thanks!

**Comment by Fritticys** [comment]
Asia has same problem

**Comment by krzt** [comment]
Same since the beginning of the year.  https://eupool.electroneum.com/# displays the correct hash rate but pending balance frozen for a long time.

**Comment by ariadhi** [comment]
It's seem they stop sending payment since January 3rd, don't have idea why this coming and I have my 50+ pending payment also and hoping someone who manage Asia and other regions solving the issue.

**Comment by agussang** [comment]
no payment from asiapool.electroneum.com, i think this coin will be scam coin. so fucking idiot thats official pool no payment. thats pool has stopped payment from 1/3/2018, and pool start fake payment on 1/7/2018 with transaction hash 15dd2b8ddbeb04f5facd232cf3e0d088fee75895d7b837b97a14b2af1c1ec667, but can't found https://blockexplorer.electroneum.com/tx/15dd2b8ddbeb04f5facd232cf3e0d088fee75895d7b837b97a14b2af1c1ec667

hahaha, let's banned this coin

**Comment by krzt** [comment]
![asia](https://user-images.githubusercontent.com/35173866/34695304-687f9398-f4db-11e7-9eab-85bd182db7ef.JPG)
![europe](https://user-images.githubusercontent.com/35173866/34695305-689d351a-f4db-11e7-8565-6e326439ba69.JPG)

**Comment by alesha17** [comment]
why until now there is no response from the manager of asiapool on this issue, appreciate the time already in the miners thanks

**Comment by ariadhi** [comment]
Do they have official contact account on Twitter or other social media?
