### ISSUE TITLE
New Pool to Add http://electroneumpool.pw

### ISSUE THREAD

**Issue by Tahrll** [electroneum/electroneum-pool#147]
Hello,

I would be very happy if you add my pool for ETN on your list.

Pool Details:
Official ETN Pool Software
Region: EU (Germany)
Fees: 0.5%
Pool Address: http://electroneumpool.pw

Best regards,
Fabian Magard

**Comment by PCPisChill** [comment]
@Tahrll How did you get this working on debian?
