### ISSUE TITLE
Can get API to run under SSL HELP! 

### ISSUE THREAD

**Issue by neurans** [electroneum/electroneum-pool#15]
Everything runs great until I activate SSL. I have modified the config.js to include https. But it does not work. The page loads and runs under ssl, but api does not. 

This runs
var api = "http://etnpool.io:8117";

this does not:
var api = "https://etnpool.io:8117";

**Comment by electroneumRepo** [comment]
You could proxy the connection in your webserver to forward requests.

We have this working using nginx

**Comment by Soyasi** [comment]
https://github.com/billaue2/cryptonote-aeon-pool/tree/master/lib con ssl

**Comment by electroneumRepo** [comment]
There have been instructions on how to do this in the README file found [here](https://github.com/electroneum/electroneum-pool#ssl)
