### ISSUE TITLE
IMP - how to back up and restore the pool on new server with all history?

### ISSUE THREAD

**Issue by cooltaby** [electroneum/electroneum-pool#153]
we wanted to move to another server, however we are afraid of losing all transaction and block found history , is there any way to back up pool and restore it on new server with all history ?

help is appreciated.
thanks

**Comment by cooltaby** [comment]
thanks for the reply, i am pretty new about this, can you share some link for tutorial or some information?

**Comment by electroneumRepo** [comment]
I'm sorry but we don't directly support mining or the pool software.

A quick google should find plenty of tutorials / info on how to backup the redis database.

Sorry we can not be of more help
