### ISSUE TITLE
new pool newpool.pw

### ISSUE THREAD

**Issue by sanich-rd** [electroneum/electroneum-pool#154]
Please add this pool to Your database. The code is unchanged it will always be! change will only web site. Fee 0.3%. The website will be supplemented by a video card, and images from the imager. This will prove small heating and the profitability of Currency. what Dates You publicity and increase the value of the coin!

**Comment by sanich-rd** [comment]
Tell me tell me this is the right setting? on zclassic?
"switching": {
"switch1": {
"enabled": true,
"algorithm": "equihash",
"ports": {
"7777": {
"diff": 10,
"varDiff": {
"minDiff": 16,
"maxDiff": 512,
"targetTime": 15,
"retargetTime": 90,
"variancePercent": 30
}
}
}
},
"switch2": {
"enabled": true,
"algorithm": "equihash",
"ports": {
"4444": {
"diff": 0.05,
"varDiff": {
"minDiff": 16,
"maxDiff": 512,
"targetTime": 15,
"retargetTime": 90,
"variancePercent": 30
}
}
}
},
"switch3": {
"enabled": true,
"algorithm": "equihash",
"ports": {
"5555": {
"diff": 1,
"varDiff": {
"minDiff": 0.001,
"maxDiff": 1,
"targetTime": 15,
"retargetTime": 60,
"variancePercent": 30

If you add komodo zcash for zdash zen As pravilno to prescribe?

Or are they machine on those ports will be?

Please tell me. On the website, only Your code.

**Comment by sanich-rd** [comment]
The site is ready. Launched Officially. Added Chat.
EU Pool ee 0.3%

What you need to add a site to the list?

**Comment by electroneumRepo** [comment]
Please open a "Pull Request" with your pool added to the README
