### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by electroneum57800** [electroneum/electroneum-pool#155]
Hello here is error which I have when I throw(launch) electroneumd:

https://zupimages.net/up/18/02/462l.png
thans you for help

**Comment by electroneumRepo** [comment]
Can you confirm which OS / Distribution you are using?

Also, Did you compile the repo yourself or use the pre-compiled binaries?

**Comment by electroneum57800** [comment]
the problem is solved

**Comment by IMYin** [comment]
How did you solve? Could you teach me?

**Comment by electroneum57800** [comment]
I am to pass in root mode(fashion) to solve concerns(marigolds)

**Comment by IMYin** [comment]
Thank you, it is solved.
