### ISSUE TITLE
etn.minepool.ch - New SWISS Electroneum pool

### ISSUE THREAD

**Issue by minepool-ch** [electroneum/electroneum-pool#169]
Can you please add the pool to the above list?

http://etn.minepool.ch

![minepool_logo](https://user-images.githubusercontent.com/35145748/34919442-5d282306-f964-11e7-9c78-bab1bab91241.png)

Hi everybody,
we are a group of miner from Switzerland: we decided to setup a mining pool for new miners willing to start easy on this hobby.
The pool is targeted for casual miners, people with low tech background on mining topic, as well as expert miners.
We provide simple instructions and preconfigured miners to be up and running in no time.
The pool is setup on a dedicated, hosted server, 1gig network.
This pool is designed beginners, expert with large rigs are more than welcome.
We provide 24/24h support: you can write an email or get real time support using our Tegram channel:@bitfanaticsmining.
You can get in touch with us to have help on rigs config and also to tell us of any issue you have with the pool.
We are small enough to give personal support to miners an change the pool config accordingly.

We pay every time a block is found, with no minimum payout.

Just visit http://etn.minepool.ch to get started.

**Comment by electroneumRepo** [comment]
Hi, please open a "Pull Request" to get your pool added to the list
