### ISSUE TITLE
Server Specs?

### ISSUE THREAD

**Issue by richardmadison** [electroneum/electroneum-pool#17]
Wondering what sort of server specs are required for the pool server?

My understanding is that the pool server simply pools others work.  Should the server have high cpu and/or high memory and/or be prepared to handle high traffic?

**Comment by electroneumRepo** [comment]
A good network connection is a must. The pool is mostly CPU intensive

**Comment by richardmadison** [comment]
Thanks @electroneumRepo .

Can you let us know what specs (AWS machine type) you guys are using for your pools?

**Comment by electroneumRepo** [comment]
We do not wish to disclose this information.

We have servers that are more than capable enough to run the pool.

We suggest you experiment with different instances if you are using AWS as ours are not cheap.
