### ISSUE TITLE
Electroneum vs Monero prefix. Is Electroneum network byte 18018 ?

### ISSUE THREAD

**Issue by bobbieltd** [electroneum/electroneum-pool#171]
Does anyone know the prefix (network byte) of Electroneum (Monero is 18) ? For ETN, it's 18018, isn't it ?

**Comment by bet0x** [comment]
It is.
` 
 uint64_t const CRYPTONOTE_PUBLIC_ADDRESS_BASE58_PREFIX = 18018;
 uint64_t const CRYPTONOTE_PUBLIC_INTEGRATED_ADDRESS_BASE58_PREFIX = 18019;
`

**Comment by bobbieltd** [comment]
@bet0x Great, it’s what I’m looking for. Thank you.
