### ISSUE TITLE
New US Cloud-Based Pool! - etnhodl.com

### ISSUE THREAD

**Issue by TrappedStudio** [electroneum/electroneum-pool#175]
Hey all,

Just started a new pool, etnhodl.com. Ran by Trapped Studio LLC. Based out of Columbus, Ohio. A little bit of a background, we are a mobile and web application company. We specialize in mobile apps. We are hoping to incorporate access to the pool to our multiple websites. 

What's the reason for the domain name? I'm sure most know but HODL isn't a misspelling. Rather it stands for Hold On (For) Dear Life. We plan to hold onto our Electroneum. We suggest others do the same. Together we can make Electroneum the #1 Cryptocurrency!

Pool Info
Address: www.etnhodl.com
Pool fee: .1%
Min Payout: 10

Thank you!

-Nathaniel T.

![logo](https://user-images.githubusercontent.com/18289701/34969448-d516a422-fa3c-11e7-990e-31ecc28f0a9e.png)

**Comment by electroneumRepo** [comment]
To get your pool added to the list, please open a "Pull Request"
