### ISSUE TITLE
New pool: etn.europepool.com

### ISSUE THREAD

**Issue by ianw1974** [electroneum/electroneum-pool#179]
Hi,

If we could please be added to the list of pools using this software, that would be great.  I'm promoting our pool to my friends and colleague, and we are hoping that it will grow and become a great place for mining electroneum.  And best of all, being apart of the community sharing the hashing power between the existing pool.s

**Comment by electroneumRepo** [comment]
Hi,

To get the pool added to the list, please open a "pull request" with your pool added to the README file
