### ISSUE TITLE
Password for admin_core_stats_massive_stuff.html

### ISSUE THREAD

**Issue by TobCar** [electroneum/electroneum-pool#18]
I just noticed a page in website_example that outputs various stats. I have tried inputting the password I set for "API" in my pool's config file but it must be returning as error as it just asks for the password again. Could this be because my pool has not mined a block yet or am I trying the wrong password?

**Comment by richardmadison** [comment]
@TobCar We're experiencing the same issue here...

**Comment by electroneumRepo** [comment]
From what I understand that means the password is incorrect. If you look in the console you should see "Admin Authorized" if the password is correct.

**Comment by cooltaby** [comment]
we are also facing same issue, not accepting password

**Comment by electroneumRepo** [comment]
In all honesty the admin page is rather useless. It only tells you the total number of registered addresses and total payments / profit.

If your having issues, open the developer console and see what error is coming back in the response when visiting the admin page.
