### ISSUE TITLE
Cannot mine on pool

### ISSUE THREAD

**Issue by jeerdo** [electroneum/electroneum-pool#180]
Hi, i set up your pool on fedora, the blockchain and wallet seems to be online, pool works and listens to ports, but i can't seems to be able to mine on any of them, neither on localhost nor from outside network.
SOCKET ERROR - [127.0.0.1:3333] invalid address used for login.

Tried different ports, tried opening ports in firewall.

**Comment by electroneumRepo** [comment]
Hi,

Fedora has not been tested and is therefore not supported. I would suggest that you install Ubuntu 16.04 and follow the instructions in the README to setup a pool correctly.
