### ISSUE TITLE
Start the pool erreur :Error getting daemon data {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":26968}

### ISSUE THREAD

**Issue by electroneum57800** [electroneum/electroneum-pool#188]
Hello here is error which I have when tries to throw(launch) my pool:
https://zupimages.net/up/18/03/5egm.png

Thank you advance for your help(assistant)

**Comment by cryptoluka** [comment]
npm install node-bignum?

**Comment by electroneum57800** [comment]
electroneum@localhost:~/redis-4.0.6/pool$ npm install node-bignum
npm ERR! code E404
npm ERR! 404 Not Found: node-bignum@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/electroneum/.npm/_logs/2018-01-21T13_40_16_225Z-debug.log
electroneum@localhost:~/redis-4.0.6/pool$


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-01-21 8:33 GMT+01:00 CryptoLuKa <notifications@github.com>:

**Comment by electroneumRepo** [comment]
What version of nodejs are you using?
Is the electroneum daemon running on the same machine?

**Comment by electroneum57800** [comment]
Hello I followed this tuto to install nodejs:
https://doc.ubuntu-fr.org/nodejs

Yes the electroneum daemon it throws when I bang the order electroneumd

2018-01-22 9:56 GMT+01:00 Richard Ells <notifications@github.com>:

**Comment by cryptoluka** [comment]
Sorry...

Instalation from https://www.npmjs.com/package/bignum

npm install bignum

it's not included in npm

**Comment by electroneum57800** [comment]
Hello I followed the tutorial: https://www.npmjs.com/package/bignum
and now I have its as message error:


electroneum@localhost:~/redis-4.0.6/pool$ node config.json
module.js:682
throw err;
^
SyntaxError: /home/electroneum/redis-4.0.6/pool/config.json: Unexpected end
of JSON input
at JSON.parse (<anonymous>)
at Object.Module._extensions..json (module.js:679:27)
at Module.load (module.js:573:32)
at tryModuleLoad (module.js:513:12)
at Function.Module._load (module.js:505:3)
at Function.Module.runMain (module.js:701:10)
at startup (bootstrap_node.js:193:16)
at bootstrap_node.js:617:3


2018-01-22 10:38 GMT+01:00 CryptoLuKa <notifications@github.com>:

**Comment by electroneum57800** [comment]
(node:24269) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

**Comment by electroneum57800** [comment]
Solved problem
