### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by richardmadison** [electroneum/electroneum-pool#19]
Ok, so beyond the basic security mentioned (redis password, etc...), can we close all inbound ports on the server except the following:

3333, 5555, 7777 (or whatever ports your allow people to connect to the pool on)
80 (for the webserver)
22 (for ssh & sFTP, ideally we should change this from 22)
8117 (for the api since the var api in the index.html page appears to call this by http://url:8117)

I'm assuming the 3 ports for the running daemons (for us: 26968 electroneumd, 8082 wallet and 6379 redis) can be closed since they're only being accessed via 127.0.0.1.

Does this make sense?

**Comment by electroneumRepo** [comment]
Required ports to confirm are as follows

1. 3333 (Mining Port)
2. 5555 (Mining Port)
3. 7777 (Mining Port)
4. 80 / 443 (Web Server)
5. 8117 (API Port - This can be proxied through your web server. There is an example in the README file for how to do this with nginx)
6. We recommend you lock down SSH / FTP to your IP address. For further security you could install a package such as FailToBan.

I hope this answers your above questions
