### ISSUE TITLE
cryptonote-util build err

### ISSUE THREAD

**Issue by webkuk** [electroneum/electroneum-pool#198]
I have problem with npm update. Any helps?

Ubuntu 17.10

npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! cryptonote-util@0.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonote-util@0.0.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the cryptonote-util package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cryptonote-util
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls cryptonote-util
npm ERR! There is likely additional logging output above.

**Comment by electroneumRepo** [comment]
I've not tested on Ubuntu 17.10 - The repository currently only supports Ubuntu 16.04 

I can only suggest that you install 16.04 and try again.

**Comment by PCPisChill** [comment]
Sam error ;_;
