### ISSUE TITLE
Blockfound no Reward.

### ISSUE THREAD

**Issue by k00lhunt3rz** [electroneum/electroneum-pool#208]
Hi i found my 4th block these are the details
b70305ffca0af3ff357f7cb2ee6a8be5d754ca8216e5ffc25b59afb4e9bc7c13:1517273253:17506103895:9276111914

And it's saying nothing in blockchain regarding this transaction neither my balance has been updated but my roundhash resetted 

What's going on is there any bug?

**Comment by bobbieltd** [comment]
What is your hashrate ? How long do you mine ? How do you know that your pool find a block ?

**Comment by k00lhunt3rz** [comment]
Hashrate is around 50 KH/S 
i know because of pool API said that i have found a block and it's showing me these details like i have found total of 4 blocks in which i have got reward for 3.

**Comment by bobbieltd** [comment]
It could be orphan block ( no reward, no existance in Bt ).

**Comment by k00lhunt3rz** [comment]
Yes i just read about orphan blocks.
Yes it could be orphan block.

Issue Closed
