### ISSUE TITLE
I have troubles installing the mining pool on windows and on ubuntu 16

### ISSUE THREAD

**Issue by icsugti** [electroneum/electroneum-pool#22]
I have troubles installing the mining pool on windows and on ubuntu 16 and I do not find any of these errors anywhere 

[Ubuntu error](https://cdn.pbrd.co/images/GRYZ9Ll.jpg)

Some help?

**Comment by electroneumRepo** [comment]
Hi,

In that image it appears that you are using windows. This is untested on windows
