### ISSUE TITLE
Buying ETN Pools

### ISSUE THREAD

**Issue by MrCoolLV** [electroneum/electroneum-pool#238]
you not interested anymore, but have miners?
i'm interested in buying pools are in use and with miners, email direct info@e.nocroom.com 

**what i will buy?**
I will buy your domain and will be redirected to our pool, not interested in your server. keep your funds in your wallet.

**Email with the following**
* domain
* your offer

Escrow is a must, once payment is in escrow
* access to domain and server must be released
* once everything is redirected via dns and confirmed working, we will shutdown your server.

**Comment by electroneumRepo** [comment]
Please do not use this to attempt to buy other peoples pools. This is an issue tracker and NOT a forum or advertising place.
