### ISSUE TITLE
Youripisbanned claymore 

### ISSUE THREAD

**Issue by electroneumfranceminage** [electroneum/electroneum-pool#240]
Hello when try to mine(undermine) with my rig I recois the message following error:Youripisbanned 

How to solve this problem?
Thank you advance for your help(assistant)

**Comment by commcad** [comment]
ehh... change IP?

You should be running off a VPN already, well if mining using 3rd party software anyway (?!) therefore easy for you to change IP/server.

If no VPN or any sort of security in place with means of changing an IP quickly, then I'm not sure what else you can do about it. Watching TV would be better/safer maybe

**Comment by electroneumRepo** [comment]
The mining script will ban an IP for submitting too many bad shares.

I believe it only bans you for 5 minutes.
