### ISSUE TITLE
invalid API call again =)

### ISSUE THREAD

**Issue by Rndexspb** [electroneum/electroneum-pool#246]
hello everybody. I've read all issuese about this but nothing helps...

so i've installed all and started the pool
config.js var api ="http://host:8117
config.json port 8117
port is opened

host:8117/stats works

host:8117 INVALID API CALL

Index.html shows only network stats

![issue](https://user-images.githubusercontent.com/36726780/36537104-31a8bb7e-17e0-11e8-8bf8-99734837ce3a.jpg)

any ideas?? was changing line in index.html from live_stats to stats and back, nothing changes.

thank you.

**Comment by electroneumRepo** [comment]
Seems like you've set something up wrong. "INVALID API CALL" is just that. The api call it's trying to make doesn't exist

**Comment by beiller** [comment]
Hey sometimes I was bitten by this. The font in the documentation looks like the call has a space " " in it, but it is actually an underscore "_". Not sure if this was monero doc or electroneum.
