### ISSUE TITLE
Cannot run npm update on pool 

### ISSUE THREAD

**Issue by dabnebula** [electroneum/electroneum-pool#26]
etnadmin@ip-172-31-23-143:~/pool$ **sudo npm update**

> cryptonote-util@0.0.3 install /home/etnadmin/pool/node_modules/cryptonote-util
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/etnadmin/pool/node_modules/cryptonote-util/build'
gyp ERR! System Linux 4.4.0-1039-aws
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/etnadmin/pool/node_modules/cryptonote-util
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptonote-util@0.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonote-util@0.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/etnadmin/.npm/_logs/2017-11-06T20_07_43_043Z-debug.log
etnadmin@ip-172-31-23-143:~/pool$ cd
etnadmin@ip-172-31-23-143:~$ vi /home/etnadmin/.npm/_logs/2017-11-06T20_07_43_043Z-debug.log
160 silly doParallel update-linked 18
161 silly doSerial install 18
162 silly install cryptonote-util@0.0.3
163 info lifecycle cryptonote-util@0.0.3~install: cryptonote-util@0.0.3
164 verbose lifecycle cryptonote-util@0.0.3~install: unsafe-perm in lifecycle false
165 verbose lifecycle cryptonote-util@0.0.3~install: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/etnadmin/pool/node_modules/cryptonote-util/node_modules/.bin:/home/etnadmin/pool/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
166 verbose lifecycle cryptonote-util@0.0.3~install: CWD: /home/etnadmin/pool/node_modules/cryptonote-util
167 silly lifecycle cryptonote-util@0.0.3~install: Args: [ '-c', 'node-gyp rebuild' ]
168 silly lifecycle cryptonote-util@0.0.3~install: Returned: code: 1  signal: null
169 info lifecycle cryptonote-util@0.0.3~install: Failed to exec install script
170 verbose unlock done using /home/etnadmin/.npm/_locks/staging-11f89cd4c7f12168.lock for /home/etnadmin/pool/node_modules/.staging
171 verbose stack Error: cryptonote-util@0.0.3 install: `node-gyp rebuild`
171 verbose stack Exit status 1
171 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
171 verbose stack     at emitTwo (events.js:126:13)
171 verbose stack     at EventEmitter.emit (events.js:214:7)
171 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
171 verbose stack     at emitTwo (events.js:126:13)
171 verbose stack     at ChildProcess.emit (events.js:214:7)
171 verbose stack     at maybeClose (internal/child_process.js:925:16)
171 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
172 verbose pkgid cryptonote-util@0.0.3
173 verbose cwd /home/etnadmin/pool
174 verbose Linux 4.4.0-1039-aws
175 verbose argv "/usr/bin/node" "/usr/bin/npm" "update"
176 verbose node v8.9.0
177 verbose npm  v5.5.1
178 error code ELIFECYCLE
179 error errno 1
180 error cryptonote-util@0.0.3 install: `node-gyp rebuild`
180 error Exit status 1
181 error Failed at the cryptonote-util@0.0.3 install script.
181 error This is probably not a problem with npm. There is likely additional logging output above.
182 verbose exit [ 1, true ]

**Comment by d3ancole1995** [comment]
You need to use node 0.10.48. You can use node version manager to install this easily

**Comment by dp-unique** [comment]
Using nvm 0.10.48 still fails for me on cryptonote-util@0.0.3 install: 'node-gyp rebuild'

**Comment by Grimm2017** [comment]
I'm getting this error as well.  What are we missing here?

**Comment by electroneumRepo** [comment]
@Grimm2017 Please ensure that you have installed all of the dependencies as outlined in the README.

@dp-unique Glad this solves it for you. We are going to create an all in one installation script for easier installation at some point in the near future.
