### ISSUE TITLE
transaction rejected by daemon (seg fault)

### ISSUE THREAD

**Issue by rvrsh3ll** [electroneum/electroneum-pool#274]
Having issues getting payments to go all of a sudden. Been working fine for months. Now it seems as though a transaction is causing a seg fault.

wallet2.cpp:3162:N5tools5error11tx_rejectedE: transaction was rejected by daemon, status = Failed, tx:

<snip>

} (double spend)
Segmentation fault (core dumped)

**Comment by rvrsh3ll** [comment]
On the daemon side when this happens:

 daemon.rpc      src/rpc/core_rpc_server.cpp:628 [on_send_raw_tx]: tx verification failed

**Comment by prox443** [comment]
Hello,
Can you send all the log lines before the Segmentation Fault message

**Comment by rvrsh3ll** [comment]
do i need to flush all tx or will that kill any payments

**Comment by rvrsh3ll** [comment]
Bump

**Comment by rvrsh3ll** [comment]
[payments] Payments splintered and 11 successfully sent, 28 failed
