### ISSUE TITLE
Cryptonote util after asic-resistance?

### ISSUE THREAD

**Issue by RustyBlock** [electroneum/electroneum-pool#277]
Hi Electroneum,

you know the way we build pool against github.com/Snipa22/node-cryptonote-util#xmr-Nan-2.0
what is going to happen after algo change for anti-asic mining?

Thanks!

**Comment by electroneumRepo** [comment]
We will be shortly releasing an update to the pool software that will enable pools to continue working seamlessly past the fork. Only miners will be required to update their mining software at the time of the fork

**Comment by RustyBlock** [comment]
Many thanks, Richard. We're looking forward to all the great things to happen in Electroneum past version 2 update.

**Comment by DeanCole** [comment]
#281 Adds the functionality for this pool software to continue working after the fork. Should get merged in tomorrow.
