### ISSUE TITLE
Bad hash from miner 

### ISSUE THREAD

**Issue by miningapps** [electroneum/electroneum-pool#279]
[pool] (Thread 1) Bad hash from miner 
(Thread 1) Share trust broken

This has started happening about 2 hours ago using this pool software. Was there any change ?

**Comment by DeanCole** [comment]
No, There have been no new changes.

It's possible the miner may have updated their mining software but it could be any number of other things as well.

**Comment by arshiay** [comment]
same issue please help

**Comment by coinergy** [comment]
I have a similar issue after latest ETN fork (ASIC friendly).
Any remedy to this issue?

**Comment by electroneumRepo** [comment]
The pool software has been updated to handle ASIC mining on V7. Please do a pull and re-run the pull, all should be good.

[Commit](https://github.com/electroneum/electroneum-pool/commit/cae1b18315a810fd4b811e5c9029ff032d0b093f)

**Comment by olalcruz** [comment]
Hi electroneumRepo. I have exactly the same issue. Bad has from miner / share trust broken. I want to do a pull as you mention but I am newbie to linux. Would you be so kind to tell my how to do a pull for this software. I would appreciate it a lot!!! Thanks in advance

**Comment by arshiay** [comment]
how you fix it please tell us

**Comment by olalcruz** [comment]
Very easy Indeed. Just follow the link that electroneum Repo is sharing on his reply and you will find a new file updated less than a month ago (pool.js). You just need to replace that file in your original directory, located in home/pool/lib. And that is all. Re run your pool and it will start accepting shares again normally. I would be a good idea if we share our emails to share experiences in the future. I am i the process of making my own mining pool but it has been very hard due I am a newbie in linux. Mine is eduardocruzc@gmail.com

**Comment by olalcruz** [comment]
Hello Guys. Simple question. I am hosting in Apache all my mining pool in just one computer in my home but when I try to see the content outside from the Internet (not from my LAN) it only displays the html content, not the dynamic info. Something is wrong with the setup of the API I think. If I maintain the 127.0.0.1 in config.js, I can see the mining pool working correctly in my LAN, but if i change this specific setup, I cant see the information in my LAN and neither through the Internet. Not loading, just the html. Can you please advice what to verify / check pls ??? I have tried to change ports but same result. Do I need to install another server to host the api data? Apache host also this data? Need some advice pls.﻿
