### ISSUE TITLE
Errors when mining under cryptonight. Problems gone when using cryptonightV7

### ISSUE THREAD

**Issue by felix920506** [electroneum/electroneum-pool#288]
I fired up claymore's miner and set it to mine cryptonight. On the side of the pool I get an error stating a bad hash every time a share is submitted. When I switch to Cryptonight V7 then It's fine. WTF???

**Comment by trans4matter** [comment]
Hi, I have same problem with xmr-stak. My pool is accepting only when using Cryptonight V7, when CryptoNight only all rejected. Using newest electroneum (5) snap.

**Comment by mannie65** [comment]
Have you actually changed the pool config algo/variant settings as well - it not enough just to run the new daemon

**Comment by trans4matter** [comment]
Wow thanks, I did not. What should I change? And to what value? I was following etn site according which only electroneumd update is needed. My config is same as before the fork.

**Comment by mannie65** [comment]
That all depends on what pool software you are using - its usually in config.json, and in a config in lib directory.

**Comment by trans4matter** [comment]
I am using this electroneum/electroneum-pool. The default [config.json](https://github.com/electroneum/electroneum-pool/blob/master/config_example.json) does only contain "coin": "electroneum", and "symbol": "ETN", without instructions how to alter anything. I understand this is just an example. I tried to adjust config based on [this](https://github.com/dvandal/cryptonote-nodejs-pool/blob/master/config_examples/electroneum.json) config which looks to me as it is using same source (also changed cnVariant to 0), but no results.

**Comment by DKusnir** [comment]
Correct solution is to remove following from pool.js file :

--------------------------------------------------------------------------------------------
var cn_variant = convertedBlob[0] >= 6 ? 1 : 0; //If v6 then use new variant else use previous
--------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------
and cn_variant from here
hash = cryptoNight(convertedBlob, cn_variant);  // 
--------------------------------------------------------------------------------------------

**Comment by trans4matter** [comment]
Thank you @mannie65 & @DKusnir . This helped. I am now accepting shares with CryptoNight.

**Comment by trans4matter** [comment]
Just using "hash = cryptoNight(convertedBlob);" and commented out "var cn_variant...". This seems to work for me.

**Comment by electroneumRepo** [comment]
The pool software has been updated to handle ASIC mining on V7. Please do a pull and re-run the pull, all should be good.

[Commit](https://github.com/electroneum/electroneum-pool/commit/cae1b18315a810fd4b811e5c9029ff032d0b093f)

**Comment by DKusnir** [comment]
we did. Initially, we rebuilt the pool from the scratch. what we saw is electroD not properly handling CN, but accepting only CNv7. Asics got all rejected shared, eventuelly got banned. This was the only fix
