### ISSUE TITLE
Frontend showing wrong hashrate of network pool

### ISSUE THREAD

**Issue by omani** [electroneum/electroneum-pool#296]
hi,

my frontend shows a hashrate of currently 10.73 GH/sec which is wrong. the network hashrate is at 6 GH/sec or something. definitely lower than 10 GH/s on ETN. I am not talking about my pool, I mean the **network** hashrate of ETN.

who else has this problem? how can this be fixed?

**Comment by electroneumRepo** [comment]
Hi,

Thanks for pointing this out.
If you fetch the latest changes then it should be all good now.
