### ISSUE TITLE
Electroneum coin source

### ISSUE THREAD

**Issue by s3479** [electroneum/electroneum-pool#33]
This is not a issue with the pool per say, I have the pool installed fine. I just can't find the Electroneum coin source to build the daemon for the pool.  Does the source exist yet? What did you use to build the pool daemon?

**Comment by s3479** [comment]
I just looked at the other issues, looks like #16 is the answer I need to follow. Let me know if I am wrong please.

**Comment by s3479** [comment]
just found it on github.

**Comment by electroneumRepo** [comment]
The coin source is available [here](https://github.com/electroneum/electroneum)

**Comment by sennevb** [comment]
i have problems compiling the wallet, i installed all dependencies:

/root/electroneum/tests/core_tests/block_validation.cpp: In member function ‘boo                                                                                                                                                             l gen_block_unlock_time_is_timestamp_in_future::generate(std::vector<boost::vari                                                                                                                                                             ant<cryptonote::block, cryptonote::transaction, cryptonote::account_base, callba                                                                                                                                                             ck_entry, serialized_object<cryptonote::block>, serialized_object<cryptonote::tr                                                                                                                                                             ansaction>, event_visitor_settings> >&) const’:
/root/electroneum/src/cryptonote_config.h:85:57: error: ‘DIFFICULTY_TARGET_V1’ w                                                                                                                                                             as not declared in this scope
 #define DIFFICULTY_BLOCKS_ESTIMATE_TIMESPAN             DIFFICULTY_TARGET_V1 //
                                                         ^
/root/electroneum/tests/core_tests/block_validation.cpp:267:87: note: in expansi                                                                                                                                                             on of macro ‘DIFFICULTY_BLOCKS_ESTIMATE_TIMESPAN’
 time = blk_0.timestamp + 3 * CRYPTONOTE_MINED_MONEY_UNLOCK_WINDOW * DIFFICULTY_
                                                                     ^
/root/electroneum/tests/core_tests/block_validation.cpp: In member function ‘boo                                                                                                                                                             l gen_block_invalid_binary_format::generate(std::vector<boost::variant<cryptonot                                                                                                                                                             e::block, cryptonote::transaction, cryptonote::account_base, callback_entry, ser                                                                                                                                                             ialized_object<cryptonote::block>, serialized_object<cryptonote::transaction>, e                                                                                                                                                             vent_visitor_settings> >&) const’:
/root/electroneum/tests/core_tests/block_validation.cpp:575:67: error: ‘DIFFICUL                                                                                                                                                             TY_TARGET_V1’ was not declared in this scope
     diffic = next_difficulty(timestamps, cummulative_difficulties,DIFFICULTY_TA
                                                                   ^
/root/electroneum/tests/core_tests/block_validation.cpp:590:65: error: ‘DIFFICUL                                                                                                                                                             TY_TARGET_V1’ was not declared in this scope
   diffic = next_difficulty(timestamps, cummulative_difficulties,DIFFICULTY_TARG
                                                                 ^
tests/core_tests/CMakeFiles/coretests.dir/build.make:86: recipe for target 'test                                                                                                                                                             s/core_tests/CMakeFiles/coretests.dir/block_validation.cpp.o' failed
make[3]: *** [tests/core_tests/CMakeFiles/coretests.dir/block_validation.cpp.o]                                                                                                                                                              Error 1
make[3]: Leaving directory '/root/electroneum/build/release'
CMakeFiles/Makefile2:2193: recipe for target 'tests/core_tests/CMakeFiles/corete                                                                                                                                                             sts.dir/all' failed
make[2]: *** [tests/core_tests/CMakeFiles/coretests.dir/all] Error 2
make[2]: Leaving directory '/root/electroneum/build/release'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/electroneum/build/release'
Makefile:62: recipe for target 'release-all' f

**Comment by electroneumRepo** [comment]
Please confirm which command you use for building?

Could you try `make release-static`

**Comment by sennevb** [comment]
I tried just make, Will try release-static and let you know

**Comment by sennevb** [comment]
it owrks with release-static, i suggest to adjust the Readme file??

**Comment by BaltoLeon** [comment]
Error: wallet failed to connect to daemon: http://localhost:26968. Daemon either is not started or wrong port was passed. Please make sure daemon is running or restart the wallet with the correct daemon address.
Restore from specific blockchain height (optional, default 0):
Error: wallet failed to connect to daemon: http://localhost:26968. Daemon either is not started or wrong port was passed. Please make sure daemon is running or restart the wallet with the correct daemon address.
Error: wallet failed to connect to daemon: http://localhost:26968. Daemon either is not started or wrong port was passed. Please make sure daemon is running or restart the wallet with the correct daemon address. 
Background refresh thread started
[wallet etnk9Y (no daemon)]:
[wallet etnk9Y (no daemon)]: etnk9YSmtumeGCYqXCfeVeTun4gfTZg9AaRffNFAD6iTJAkKw6LgJUs4N75xSGvPzyBVotx4XYSEpKDAs3P39KeM24DxqGFtsZ
unknown command: etnk9YSmtumeGCYqXCfeVeTun4gfTZg9AaRffNFAD6iTJAkKw6LgJUs4N75xSGvPzyBVotx4XYSEpKDAs3P39KeM24DxqGFtsZ
[wallet etnk9Y (no daemon)]:
[wallet etnk9Y (no daemon)]:
[wallet etnk9Y (no daemon)]:
[wallet etnk9Y (no daemon)]: etnk9YSmtumeGCYqXCfeVeTun4gfTZg9AaRffNFAD6iTJAkKw6LgJUs4N75xSGvPzyBVotx4XYSEpKDAs3P39KeM24DxqGFtsZ
unknown command: etnk9YSmtumeGCYqXCfeVeTun4gfTZg9AaRffNFAD6iTJAkKw6LgJUs4N75xSGvPzyBVotx4XYSEpKDAs3P39KeM24DxqGFtsZ
[wallet etnk9Y (no daemon)]:
[wallet etnk9Y (no daemon)]: etnk9YSmtumeGCYqXCfeVeTun4gfTZg9AaRffNFAD6iTJAkKw6LgJUs4N75xSGvPzyBVotx4XYSEpKDAs3P39KeM24DxqGFtsZ
unknown command: etnk9YSmtumeGCYqXCfeVeTun4gfTZg9AaRffNFAD6iTJAkKw6LgJUs4N75xSGvPzyBVotx4XYSEpKDAs3P39KeM24DxqGFtsZ
[wallet etnk9Y (no daemon)]:
WHAT DO I HAVE TO DO ? THANKS

**Comment by electroneumRepo** [comment]
@sennevb I will adjust the README file

@BaltoLeon 
> Error: wallet failed to connect to daemon: http://localhost:26968. Daemon either is not started or wrong port was passed. Please make sure daemon is running or restart the wallet with the correct daemon address.
Restore from specific blockchain height (optional, default 0):
Error: wallet failed to connect to daemon: http://localhost:26968. Daemon either is not started or wrong port was passed. Please make sure daemon is running or restart the wallet with the correct daemon address.
Error: wallet failed to connect to daemon: http://localhost:26968. Daemon either is not started or wrong port was passed. Please make sure daemon is running or restart the wallet with the correct daemon address.
Background refresh thread started
[wallet etnk9Y (no daemon)]:
[wallet etnk9Y (no daemon)]: etnk9YSmtumeGCYqXCfeVeTun4gfTZg9AaRffNFAD6iTJAkKw6LgJUs4N75xSGvPzyBVotx4XYSEpKDAs3P39KeM24DxqGFtsZ
unknown command: etnk9YSmtumeGCYqXCfeVeTun4gfTZg9AaRffNFAD6iTJAkKw6LgJUs4N75xSGvPzyBVotx4XYSEpKDAs3P39KeM24DxqGFtsZ
[wallet etnk9Y (no daemon)]:
[wallet etnk9Y (no daemon)]:
[wallet etnk9Y (no daemon)]:
[wallet etnk9Y (no daemon)]: etnk9YSmtumeGCYqXCfeVeTun4gfTZg9AaRffNFAD6iTJAkKw6LgJUs4N75xSGvPzyBVotx4XYSEpKDAs3P39KeM24DxqGFtsZ
unknown command: etnk9YSmtumeGCYqXCfeVeTun4gfTZg9AaRffNFAD6iTJAkKw6LgJUs4N75xSGvPzyBVotx4XYSEpKDAs3P39KeM24DxqGFtsZ
[wallet etnk9Y (no daemon)]:
[wallet etnk9Y (no daemon)]: etnk9YSmtumeGCYqXCfeVeTun4gfTZg9AaRffNFAD6iTJAkKw6LgJUs4N75xSGvPzyBVotx4XYSEpKDAs3P39KeM24DxqGFtsZ
unknown command: etnk9YSmtumeGCYqXCfeVeTun4gfTZg9AaRffNFAD6iTJAkKw6LgJUs4N75xSGvPzyBVotx4XYSEpKDAs3P39KeM24DxqGFtsZ
[wallet etnk9Y (no daemon)]:
WHAT DO I HAVE TO DO ? THANKS

Firstly, you should not hook onto other peoples tickets and this should also not be asked on this repository.

In answer to your question.

You need to run the daemon.
Your output that you have pasted clearly states `no daemon`

The daemon MUST be fully synced with the blockchain and running BEFORE using the electroneum-wallet-cli
