### ISSUE TITLE
Mining to the pool, STATS api not working (Amazon EC2 instance)

### ISSUE THREAD

**Issue by dyablohunter** [electroneum/electroneum-pool#35]
Hi guys,

I have a friend working on deploying the pool on amazon EC2 services, I am a big fan of ETN and I want to support Electroneum by creating a reliable and auto-scaling pool so that everyone can mine without any issues, so far all the pools I have mined in are very unstable and unreliable.

My friend deployed everything correctly, I am able to mine to the pool, results are accepted by the pool, but the STATS api is not working, I can't see any statistics from the pool or blockchain in any of the pages from the front end.

Is there anyone that can help us deploy this pool on amazon hosting?

Thanks.

**Comment by electroneumRepo** [comment]
Hi,

If the stats are not working then this a configuration issue.

By default the API part of the pool is listening on port 8117. This will need to be open in your amazon security group.

You also need to make sure that the `api` variable in the config.js includes that port (e.g var api = "http://yourpool.com:8117";

Hope this helps.

**Comment by dyablohunter** [comment]
![error](https://user-images.githubusercontent.com/6419567/32836306-f8c55d7e-ca11-11e7-8264-090a0e6b1095.png)
This is what I see in the console.

**Comment by electroneumRepo** [comment]
You have some issue in your config.js file.

If you see in your js file. You have a "~" on its own at the bottom. You should remove this and then it can be okay. You also need to correct your "api" variable
