### ISSUE TITLE
multi-hashing@0.0.9 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by bapparabi** [electroneum/electroneum-pool#43]
hoe can i solve this issue 

`npm ERR! Linux 2.6.32-042stab125.5
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "update"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! multi-hashing@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the multi-hashing@0.0.9 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the multi-hashing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs multi-hashing
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls multi-hashing
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pooladmin/pool/npm-debug.log
pooladmin@etn:~/pool$ ^C
pooladmin@etn:~/pool$
`

**Comment by electroneumRepo** [comment]
It looks like your using a newer version of node.js

The pool currently works on node js 0.10.48
