### ISSUE TITLE
coinUnits = ?

### ISSUE THREAD

**Issue by cheebeez** [electroneum/electroneum-pool#44]
Hello. In frontend "coinUnits" = 100, but in [electroneumd src](https://github.com/electroneum/electroneum/blob/5425662040043092f4ff75d549327ef0f3e43839/src/cryptonote_config.h#L64) COIN option = 1000000000000

I do not understand which of these numbers to use in cryptonote-universal-pool/config.json

```
/* Used for front-end display */
"symbol": "ETN",

/* Minimum units in a single coin, see COIN constant in DAEMON_CODE/src/cryptonote_config.h */
"coinUnits": 1000000000000,
```

Thanks for help.

**Comment by electroneumRepo** [comment]
Hi,

`coinUnits` should be `100`.

Thanks for pointing that out in the daemon source, I'll look into that
