### ISSUE TITLE
I got "Invalid api call" after started pool and get display pool stats in website

### ISSUE THREAD

**Issue by bobekook** [electroneum/electroneum-pool#47]
Hi All,

I test create the electroneum-pool in VM VirtualBox with Ubuntu 16.04 before set up in live server.
When pool, api, unlocker and payments is started, I can connect with miner client (Claymore CryptoNote AMD GPU Miner v10.2) and send hashrate to my pool.
        
After that i test direct access pool api with http://localhost:8117/api/stats i got "Invalid api call"
After that i test run website_example in apache2  and try to access index.html for display pool stats information with localhost  i got same error "Invalid api call" when my website GET http://localhost:8117/api/stats . 

Please guide me for solve this and can get display pool stats information in localhost website (index.html). 

Api started
https://ibb.co/ksutiR

Miner connected
https://ibb.co/bDJfV6

website_example/config.js
-------------------------------------------------------------------
var api = "http://localhost:8117/api";
var coinUnits = 100;
var coinDecimalPlaces = 2;
var poolHost = "localhost";
var irc = "irc.freenode.net/#monero-pools";
var email = "support@electroneum.com";
var easyminerDownload = "https://github.com/zone117x/cryptonote-easy-miner/releases/";
var blockchainExplorer = "https://blockexplorer.electroneum.com/block/";
var transactionExplorer = "https://blockexplorer.electroneum.com/tx/";

And i can not access admin_core_stats_massive_stuff.html this page is required password admin. Where can I set/get this password?

Thank you.

**Comment by electroneumRepo** [comment]
Hi,

Firstly, can you please confirm whether you are running this locally or on a remote server.

Secondly, I do not know the way you set this up but judging by your `config.js` I would say your `var api = "http://localhost:8117/api";` is the issue. Try changing this to `var api = "http://localhost:8117";`

Lastly, the admin password is in the config.json in the root of the pool directory.

I hope this helps.

**Comment by bobekook** [comment]
Hi Sir,

Your solution is success for me.

I try to change api url in config.js from "http://localhost:8117/api"; to "http://localhost:8117";
I can get pool stats information with api now.
https://ibb.co/kjbRoR

And i can access admin_core_stats_massive_stuff.html page.

Thank you very much.

**Comment by electroneumRepo** [comment]
Glad to help.

I'll no close this issue.
