### ISSUE TITLE
How to run wallet RPC server in background ?

### ISSUE THREAD

**Issue by bobekook** [electroneum/electroneum-pool#53]
Hi all

After start  `./electroneumd --detach` in background process.

I need to run step below in background process , but i can not use `--detach` and `forever start` it not work.
> Lastly you need to start the wallet RPC server which makes the payments to your miners. This can be started using ./electroneum-wallet-rpc --wallet-file walletfilename --password walletfilepassword --rpc-bind-port 26969 --disable-rpc-login

Please guild me for example command for run `./electroneum-wallet-rpc` in background process.

Thank you

**Comment by electroneumRepo** [comment]
We use `screen` on linux to run our processes.

This allows you to easily attach the process if there is ever a problem.

**Comment by rwalkos** [comment]
sudo apt install screen
screen -S daemond <--- Use to run the daemond
screen -S rpc <---- Use to run rpc
screen -S website < --- use to run website
etc.

screen -list <---- List screens
screen -r website <--- reconnect to screen website

CTRL + a then CTRL + d <----- detatch from a screen

**Comment by wanchanas** [comment]
Ok, I see.
I will try with your solution.

Thank you.

**Comment by kostasmoure** [comment]
hi all,
i have the same question. If i use screen and close the terminal, will be runing in backround?
My main problems are 3.
Make init.js runs even if the system reboot-restart
Make  ./electroneumd run even if the system reboot-restart
Make electroneum-wallet-rpc run even if the system reboot-restart

I have read that ./electroneumd may be started as system service placing inside /lib/systemd/system electroneumd.service. I will try that now. But the 2 others cant figure out how to make them run automatic even if i close terminal...

Thank you in advance

**Comment by goodthebest** [comment]
If you use 'screen' to keep process running, you can simply detach screen, just press Ctrl A D  together.

Regarding starting at reboot you can check, rc.local, you need to run bash script.
