### ISSUE TITLE
cannot find module 'multi-hashing'

### ISSUE THREAD

**Issue by waflu** [electroneum/electroneum-pool#54]
Hi, I build electroneum repo, make wallet and configured config.json but pool have problem with "multi-hashing".  I have done npm update.

````
2017-11-27 09:57:23 [master] Pool spawned on 1 thread(s)
2017-11-27 09:57:24 [unlocker] Started
2017-11-27 09:57:24 [payments] Started
2017-11-27 09:57:24 [unlocker] No blocks candidates in redis
2017-11-27 09:57:24 [payments] No workers' balances reached the minimum payment threshold
2017-11-27 09:57:24 [api] API started & listening on port 8117
2017-11-27 09:57:24 [api] Stat collection finished: 53 ms redis, 51 ms daemon
2017-11-27 09:57:24 [api] Broadcasting to 0 visitors and 0 address lookups
module.js:544
    throw err;
    ^

Error: Cannot find module 'multi-hashing'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/pool/lib/pool.js:7:20)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
2017-11-27 09:57:24 [master] Pool fork 1 died, spawning replacement worker...
^C

````

**Comment by electroneumRepo** [comment]
Can you confirm that your `npm update` finished successfully?

Could you also confirm which version of node.js you are using.

Support of this pool is only for node 0.10.48

**Comment by waflu** [comment]
I'm using the latest version od nodejs. How can I install 0.10.48?

**Comment by waflu** [comment]
I have now node 0.10.48, I can't do npm update successfully here is output:
`> cryptonote-util@0.0.3 install /root/pool/node_modules/cryptonote-util
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/root/pool/node_modules/cryptonote-util/build'
  CXX(target) Release/obj.target/cryptonote/src/main.o
In file included from ../../nan/nan.h:199:0,
                 from ../src/main.cc:15:
../../nan/nan_maybe_pre_43_inl.h: In function 'Nan::Maybe<bool> Nan::DefineOwnProperty(v8::Handle<v8::Object>, v8::Handle<v8::String>, v8::Handle<v8::Value>, v8::PropertyAttribute)':
../../nan/nan_maybe_pre_43_inl.h:158:44: warning: suggest parentheses around '& ' within '||' [-Wparentheses]
                  !(current & v8::ReadOnly) &&               // writable AND
                                            ^
  CXX(target) Release/obj.target/cryptonote/src/cryptonote_core/cryptonote_format_utils.o
../src/cryptonote_core/cryptonote_format_utils.cpp: In function 'bool cryptonote::check_proof_of_work(const cryptonote::block&, cryptonote::difficulty_type, crypto::hash&)':
../src/cryptonote_core/cryptonote_format_utils.cpp:938:3: warning: no return statement in function returning non-void [-Wreturn-type]
   }
   ^
  CC(target) Release/obj.target/cryptonote/src/crypto/tree-hash.o
  CXX(target) Release/obj.target/cryptonote/src/crypto/crypto.o
  CC(target) Release/obj.target/cryptonote/src/crypto/crypto-ops.o
  CC(target) Release/obj.target/cryptonote/src/crypto/crypto-ops-data.o
  CC(target) Release/obj.target/cryptonote/src/crypto/hash.o
  CC(target) Release/obj.target/cryptonote/src/crypto/keccak.o
  CXX(target) Release/obj.target/cryptonote/src/common/base58.o
  SOLINK_MODULE(target) Release/obj.target/cryptonote.node
  COPY Release/cryptonote.node
make: Leaving directory '/root/pool/node_modules/cryptonote-util/build'
npm WARN unmet dependency /root/pool/node_modules/multi-hashing requires nan@'1' but will load
npm WARN unmet dependency /root/pool/node_modules/nan,
npm WARN unmet dependency which is version 2.8.0
npm WARN unmet dependency /root/pool/node_modules/node-multi-hashing requires nan@'1' but will load
npm WARN unmet dependency /root/pool/node_modules/nan,
npm WARN unmet dependency which is version 2.8.0
cryptonote-util@0.0.3 node_modules/cryptonote-util
npm ERR! Linux 2.6.32-042stab120.16
npm ERR! argv "/root/.nvm/v0.10.48/bin/node" "/root/.nvm/v0.10.48/bin/npm" "update"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! path /root/pool/node_modules/node-multi-hashing
npm ERR! code EISGIT

npm ERR! git Appears to be a git repo or submodule.
npm ERR! git     /root/pool/node_modules/node-multi-hashing
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/pool/npm-debug.log
`

I will try delete npm and nodejs and try again.

**Comment by mrntidu** [comment]
$ npm install multi-hashing

**Comment by mrntidu** [comment]
$ npm update
