### ISSUE TITLE
Cmake errors occurred

### ISSUE THREAD

**Issue by MRTN87** [electroneum/electroneum-pool#58]
I am setting up a pool and when I am trying to do **cmake .** it tells me that configuring it's incomplete.
Here's CMakeError.log: https://pastebin.com/qu6pf1ZQ

**Comment by electroneumRepo** [comment]
There is no reason to run "cmake"

You should simply run `make release-static` (on linux)

Which OS you are using?
Which version of nodejs are you using?
Have you installed all of the dependencies?

**Comment by MRTN87** [comment]
I fixed this after I installed 16.04. Thanks ! Now I have another problem.
