### ISSUE TITLE
how to remove getting started text from home page?

### ISSUE THREAD

**Issue by cooltaby** [electroneum/electroneum-pool#61]
we want to redesing the home page of mining pool but we are unable to remove getting started text and download buttons from home page which has dev id 'siteInfo'.

Please help us to customise. thanks

**Comment by MRTN87** [comment]
Edit home.html
Just copy everything from here: https://pastebin.com/0cAcUQMc and paste it in your home.html that's located in web-example/pages.

**Comment by cooltaby** [comment]
thanks it worked.
