### ISSUE TITLE
Deamon CPU

### ISSUE THREAD

**Issue by ddvs1** [electroneum/electroneum-pool#70]
Hi guys,

seams deamon are having a lot a CPU intensive task, don't you guys think this values to hight?

 "blockRefreshInterval": 1000,

  "updateInterval": 3,

i change that and the server are much better, any reason to the values are like that?

Luis

**Comment by electroneumRepo** [comment]
Hi,

These values are the default values that came when we forked the pool.

We have experimented with different values on our servers and worked out the best for our own pools.

You should do the same for your and configure as necessary.

**Comment by ddvs1** [comment]
Hi @electroneumRepo 

i dont think so in case CPU related, try this ones and see overall CPU in the pools will down.

        "blockRefreshInterval": 29000,

 "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 59,

and let me know.

Luis
