### ISSUE TITLE
payment stuck in pending balance (important )

### ISSUE THREAD

**Issue by cooltaby** [electroneum/electroneum-pool#75]
got logs 
 Error with transfer RPC request to wallet daemon {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}

and 
payment threshold
 now its in payment info log txt
 2017-12-07 02:24:53 Started
2017-12-07 02:24:53 Payments splintered and 0 successfully sent, 2 failed

please help balance is in unlocked state

**Comment by electroneumRepo** [comment]
Hi,

You need to configure your ports correctly in the config file.

To send payments, you need to be running the RPC wallet.

Please be sure to check you have followed all the instructions in the README file.

**Comment by ddvs1** [comment]
Yaa,

check the ports, i have the problem before.

**Comment by cooltaby** [comment]
—rpc-bind-port 8082 
matches your config 
 "wallet": {
        "host": "127.0.0.1",
        "port": 8082
    },
checked all fine

**Comment by cooltaby** [comment]
RPC wallet is ruuning

**Comment by ddvs1** [comment]
I Use this.

sudo ./electroneum-wallet-rpc --wallet-file poolwallet --password pass --rpc-bind-port 26969 --disable-rpc-login

sudo ./electroneumd --detach

   "daemon": {
        "host": "127.0.0.1",
        "port": 26968
    },
    "wallet": {
        "host": "127.0.0.1",
        "port": 26969
    },
    "redis": {
        "host": "127.0.0.1",
        "port": 6379,
        "auth": null


i hope that helps.

Luis

**Comment by cooltaby** [comment]
thanks luis for answer, so i ran this comman now i need to change my daemon and wallet port as per above in config.js and any other place where i need to update it?

**Comment by cooltaby** [comment]
after first command its still on WARN    wallet.rpc      src/wallet/wallet_rpc_server.cpp:1898   Starting wallet rpc server
 waiting for it to enter second command sudo ./electroneumd --detach

**Comment by ddvs1** [comment]
change in config.json , and restart both services

**Comment by cooltaby** [comment]
but its stuck on starting wallet server line

**Comment by ddvs1** [comment]
Remember

1st :    sudo ./electroneumd --detach

2nd: sudo ./electroneum-wallet-rpc --wallet-file poolwallet --password pass --rpc-bind-port 26969 --disable-rpc-login

change your wallet file and password to yours

**Comment by ddvs1** [comment]
This need to be changed to your info: --wallet-file poolwallet --password pass

**Comment by cooltaby** [comment]
2017-12-07 09:32:45.134     7fba19137740        WARN    wallet.rpc      src/wallet/wallet_rpc_server.cpp:1853   Loading wallet...
2017-12-07 09:32:45.163     7fba19137740        WARN    wallet.wallet2  src/wallet/wallet2.cpp:2497     Loaded wallet keys file, with public address: etnkBgDU1o82U4YTUqNuMh1c5ptADfaJtYCoz633FDdwwexXYF3CJEKVDDqeMQArorC7jWSHHCtgwU8t1sJUnonXp53jvtupr3U
2017-12-07 09:32:49.065     7fba19137740        INFO    global  contrib/epee/include/net/http_server_impl_base.h:70     Binding on 127.0.0.1:26969
2017-12-07 09:32:49.065     7fba19137740        WARN    wallet.rpc      src/wallet/wallet_rpc_server.cpp:1898   Starting wallet rpc server

followed step 1 and 2 > after step 2 > does not proceed further

**Comment by cooltaby** [comment]
7-12-07 09:33:48.213       [SRV_MAIN]      WARN    wallet.rpc      src/wallet/wallet_rpc_server.cpp:1900   Stopped wallet rpc server
2017-12-07 09:33:48.213 [SRV_MAIN]      WARN    wallet.rpc      src/wallet/wallet_rpc_server.cpp:1903   Storing wallet...
2017-12-07 09:33:48.273 [SRV_MAIN]      WARN    wallet.rpc      src/wallet/wallet_rpc_server.cpp:1905   Stored ok

**Comment by cooltaby** [comment]
later i got this

**Comment by ddvs1** [comment]
did you create a internal wallet with CLI ?

**Comment by cooltaby** [comment]
yes, its created with CLI

**Comment by cooltaby** [comment]
is it possible to connect with me on skype, discord or telegram?

**Comment by ddvs1** [comment]
Need to work then.

What says Payments error log ?


Melhores Cumprimentos,

Maletazul Lda
Luis Silva
+351.916211270
www.maletazul.pt<x-msg://832/www.maletazul.pt>
www.facebook.com/maletazul<x-msg://832/www.facebook.com/maletazul>

On-Line Store:
http://loja.maletazul.pt<http://lojani.maletazul.pt/>
https://www.facebook.com/MaletazulLojaNativeInstruments/


CCNA – CCDA - VCP – VSTP – VMTSP - VMSP - EMC´s VNX – MCSE
[cid:image001.png@01D36F3F.4315A0B0]

**Comment by ddvs1** [comment]
Shure

**Comment by cooltaby** [comment]
telegrame @razzeru  discord @ razzeru#3160

**Comment by cooltaby** [comment]
[payments_error.log](https://github.com/electroneum/electroneum-pool/files/1538544/payments_error.log)

**Comment by cooltaby** [comment]
[payments_info.log](https://github.com/electroneum/electroneum-pool/files/1538545/payments_info.log)

**Comment by ddvs1** [comment]
https://discord.gg/K3ReYc

**Comment by cooltaby** [comment]
@ddvs1  thanks for solving the issue, i really appreciate your time and effort to the etn community

**Comment by electroneumRepo** [comment]
Glad you got it sorted.

If you could post what the issue was then it may help others in the future

**Comment by ddvs1** [comment]
Shure @electroneumRepo 

After setup correctly the ports,

just run this sudo ./electroneum-wallet-rpc --wallet-file poolwallet --password pass --rpc-bind-port 26969 --disable-rpc-login --trusted-daemon

with the --trusted-daemon added to the inicial command from cooltaby.

I hope that helps

Luis

**Comment by ddvs1** [comment]
@electroneumRepo Btw can you please add our pool to your list?

www.west-pool.org

thank you.
