### ISSUE TITLE
 Error: failed to load wallet: failed to read file "xyz"

### ISSUE THREAD

**Issue by cooltaby** [electroneum/electroneum-pool#77]
![image](https://user-images.githubusercontent.com/12084138/33760944-7e33b834-dc2d-11e7-88c0-2e0e67fd3c92.png)

yesterday our server was shutdown, today i tried 
cd electroneum
./electroneum-wallet-cli 
then wallet name and correct password but getting  Error: failed to load wallet: failed to read file "xyz"

please help before we get the another block

**Comment by seminara** [comment]
sudo ./electroneum-wallet-cli
make sure you sudo

**Comment by electroneumRepo** [comment]
Don't use `sudo`
What user did you create the wallet with? If it was root then please regenerate the file under a normal non-root user and try again.
