### ISSUE TITLE
Cant run electroneum daemon after sync

### ISSUE THREAD

**Issue by cissrawk** [electroneum/electroneum-pool#82]
hello, i cant run daemon. I already sync it for almost 3 days. But when i open i cant use it. It said like on the picture. After that it force close instantly.
![image](https://user-images.githubusercontent.com/24662427/33794878-f3d192f8-dd06-11e7-8a2e-b086cd1cb784.png)

How to fix this ?

**Comment by AgentCrypto** [comment]
try to run with sudo 
reboot
