### ISSUE TITLE
First Chinese pool. Hope to be listed in the readme.md

### ISSUE THREAD

**Issue by tuoxiansp** [electroneum/electroneum-pool#86]
Hi, our pool is online recently.
We are writing articles in Chinese community and "QQ group" to intrtiroduce ETN to Chinese miners.

Our pool address: [http://etn.nutpool.net/](http://etn.nutpool.net/)

**Comment by electroneumRepo** [comment]
@tuoxiansp 
Please open a pull request to get your pool added to the list
