### ISSUE TITLE
How to configure Nginx for this pool ?

### ISSUE THREAD

**Issue by BatLesStakes** [electroneum/electroneum-pool#89]
Hey, is it possible to have a tutorial on how to setup Nginx for this pool ?
I found nowhere how to, some help will be greatly appreciated.
Thanks

BatLesStakes

**Comment by electroneumRepo** [comment]
@BatLesStakes I'm sorry but this is not something that we can help with. Running a pool is not a simple task. If you need help setting up nginx then I can only suggest that you google for help.

It is quite easy to install and setting it up is not all that difficult. You'll find help on sites such as "StackOverflow"

**Comment by AgentCrypto** [comment]
https://linode.com/docs/web-servers/nginx/how-to-configure-nginx/
